### PR TITLE
BCB-1159 -> development

### PR DESCRIPTION
**Pull request by blohre-usgs**

### CODE REVIEW

**Comment by skybristol** [comment]
Did we get the spatial feature registry part of this idea figured out already, or is this user feature getting out ahead of that infrastructure? I think it was the internal repo where I posted an issue about creating a capability to process an uploaded shapefile or the selected features from that upload into a data store of some kind, recording at least the implicit metadata about the context and maybe building in a feature down the road to let the user supply some further information. Is that part of this yet?

The reason I'm on this issue comes from lessons learned with the HLT app where we did not build in some ability to collect at least a little bit of a record on what users are doing with the app. In that case, we've realized a huge missed opportunity that I don't want to repeat here.

**Comment by brownd-usgs** [comment]
Short answer: no, we aren't saving anything about the user's shapefile upload.

We can look into building that stuff in though. Collecting the geometry and some metadata sounds easy enough. I can work out the details with Steve? Do we want to hold up this version for the added features (saving the metadata and geometry)?

**Comment by skybristol** [comment]
It's @aulenbac 's call, but I'd rather not roll out the feature to production until we have a MVP on stashing features from uploads. If this feature is running somewhere on staging, I'd love to have a look. I'm not familiar enough with the code to dig in and understand what I'm looking at.

I'm curious about what all types of features you are accepting for the process (polygon, multipolygon, point/line with buffer, etc.). I'm also curious to know if you are building this in at a fundamental API level first and then driving the user interface from that API.

I think we would want to record the following as an initial MVP:

- registered identifier assigned by our system and used for tracking back to URL trace on operations against the uploaded feature of interest
- date/time of the upload
- inbound IP of the uploading browser (not reliable for much but some metrics eval)
- file digest (filenames, dates)
- basic characteristics of the overall data package uploaded (number of features, property names included, type of properties) in JSON Schema or something like it
- full XML metadata if it was included in the upload (we can talk about what to try and pull from this down the road)
- geometry with projection of selected feature(s) (however we opt to convert and store - geojson, etc.)
- any properties associated with the feature(s) from the DBF

* Failed uploads should be logged somewhere for us to examine what went wrong in terms of being able to process the shapefile.

Also, if we're going to do shapefiles, then we should go ahead and accommodate some other types of feature initiation in the same architectural component - GeoJSON files, etc.

**Comment by brownd-usgs** [comment]
First iteration, which we just put on dev-is (internal only) accepts only a 'polygon' shapefile. Additionally it needs to be under 5MB and will only use the FIRST polygon in the dataset as the AOI. We can definitely add functionality to accept some other formats (GeoJSON). We can also add functionality to accept other geometries (points, lines), but we don't have any BAPs that currently use those...

**Comment by brownd-usgs** [comment]
https://dev-sciencebase.usgs.gov/biogeography/
The 'upload shapefile' button is in the upper-right by the 'draw polygon' button.

**Comment by skybristol** [comment]
The UI could use some improvements. Without some kind of status bar idea, the user has no feedback that anything is happening with their upload action. We need to take people into a dialog/action area of some kind where they see what's happening. Probably should give them a quick look at the geometry they are about to send to the map in a preview/thumbnail as feedback.

Limiting upload size and only the first polygon basically means that we are asking the user to just use this as a means of supplying geometry. I get that, but it doesn't give us anything useful to examine over time about what users are doing and why as they will likely just clip out the geo and strip everything else interesting out of the file that we would want to introspect. We should really think instead of breaking up the whole process and building out a loosely coupled module that handles the registry of some new dataset of interest from any number of sources, including existing online services like a WFS somewhere.

Points and lines as AOI input is a separate matter; I just wondered if it had been dealt with yet.

**Pull request merged**
